baseURL: "https://mathildecol.github.io"
title: Mathilde Col
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /research/
          weight: 1
        - name: CV
          url: /cv/
          weight: 2

params:
    description: "I am a PhD student at the Bordeaux School of Economics, under the supervision of Tanguy Bernard (BSE) and Denis Cogneau (PSE). I am interested in education in Africa, and especially the languages of instruction issue."
    author: Mathilde Col
    #googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title : Mathilde Col
          subtitle: "I am a PhD student at the [Bordeaux School of Economics](https://www.bse.u-bordeaux.fr/), under the supervision of [Tanguy Bernard (BSE)](https://sites.google.com/view/tanguybernard/home) and [Denis Cogneau](https://www.parisschoolofeconomics.eu/fr/cogneau-denis/) (PSE). I am interested in education in Africa, and especially the languages of instruction issue."
          imageUrl: "/ID.jpg"
          imageWidth: 250
          imageHeight: 250
          imageTitle: Mathilde Col
          buttons:
            - name: Research
              url: /research/
            - name: CV
              url: /cv/Academic_CV_2023.pdf
    socialIcons:
        - name: Email
          url: mailto:mathilde.col@gmail.com
        - name: OrCID
          url: https://orcid.org/0009-0005-3475-2969
        - name : Twitter
          url : https://twitter.com/colmathe
        - name: LinkedIn
          url: https://www.linkedin.com/in/mathilde-col/
        - name: GitHub
          url: https://github.com/colmate
        - name: Location
          url: /location/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Mathilde Col"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
